// <auto-generated />
namespace PracticeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAttendances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAttendances));
        
        string IMigrationMetadata.Id
        {
            get { return "201907080549500_addAttendances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
